# render.yaml
services:
  # 1) API FastAPI en backend/
  - type: web
    name: optimizacion-inventario-api
    env: python             # ← fuerza uso de Python, ignora package.json en frontend
    plan: free
    branch: main
    workingDirectory: backend

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    healthCheckPath: /

  # 2) Frontend estático desde frontend/src
  - type: static
    name: optimizacion-inventario-frontend
    branch: main

    staticPublishPath: frontend/src
    buildCommand: echo "No build needed"
    envVars:
      - key: RENDER_REDIRECT_ROOT
        value: "true"
