# render.yaml
services:
  - type: web
    name: optimizacion-inventario-api
    env: python
    plan: free
    branch: main

    # Antes de todo: instalamos dependencias Python
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements.txt

    # Arrancamos uvicorn apuntando a tu main.py dentro de backend/
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT

    # Comprueba que "/" sirva tu index.html
    healthCheckPath: /
